name: flutter_vector_icons
description: >-
  Customizable Icons for Flutter. Port of react-native-vector-icons
version: 2.0.0
homepage: https://github.com/git-touch/flutter-vector-icons
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  fonts:
    - family: AntDesign
      fonts:
        - asset: fonts/AntDesign.ttf
    - family: Entypo
      fonts:
        - asset: fonts/Entypo.ttf
    - family: EvilIcons
      fonts:
        - asset: fonts/EvilIcons.ttf
    - family: Feather
      fonts:
        - asset: fonts/Feather.ttf
    - family: FontAwesome
      fonts:
        - asset: fonts/FontAwesome.ttf
    - family: FontAwesome5_Brands
      fonts:
        - asset: fonts/FontAwesome5_Brands.ttf
    - family: FontAwesome5_Regular
      fonts:
        - asset: fonts/FontAwesome5_Regular.ttf
    - family: FontAwesome5_Solid
      fonts:
        - asset: fonts/FontAwesome5_Solid.ttf
    - family: Fontisto
      fonts:
        - asset: fonts/Fontisto.ttf
    - family: Foundation
      fonts:
        - asset: fonts/Foundation.ttf
    - family: Ionicons
      fonts:
        - asset: fonts/Ionicons.ttf
    - family: MaterialCommunityIcons
      fonts:
        - asset: fonts/MaterialCommunityIcons.ttf
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons.ttf
    - family: Octicons
      fonts:
        - asset: fonts/Octicons.ttf
    - family: SimpleLineIcons
      fonts:
        - asset: fonts/SimpleLineIcons.ttf
    - family: Zocial
      fonts:
        - asset: fonts/Zocial.ttf
